---
title: "Homework 11"
author: "Emily Beasley"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)
library(patchwork)
library(viridis)
library(metacom)
```

The graphs generated by this code 1) observation error can drastically bias estimates when species are detected imperfectly, and 2) display the abundance of each species at each site for true and observed data.

```{r Abundance Data}
#Load abundance data
site.abund <-readRDS(file = "siteabund.rds")

#change column names
colnames(site.abund) <- c("Rank", "Estimated", "Observed", "True")
site.abund$Site <- seq(1:30)

#Put it into long format
site.abund %>%
  gather(Estimated:True, key = "Source", value = "Abundance") %>%
  {. ->> siteabund}
```

```{r Species Heatmap Data}
#Load data
truemamm <- readRDS(file = "truemamm.RDS")
truemamm <- as.data.frame(t(truemamm))

obsmamm <- readRDS(file = "obsdata.RDS")
maxobs <- as.data.frame(apply(obsmamm, c(1,3), max))

long.dat <- function(x){
  x$Site <- seq(1:30)
  
  x %>%
    gather(V1:V10, key = "Species", value = "Abundance")
}

long.tru <- long.dat(truemamm)
long.obs <- long.dat(maxobs)
```

```{r Graph It, fig.width = 8}
#Comparing true abundances with observed data and estimates from an MSAM
abund <- ggplot(data = siteabund, aes(x = Rank, y = Abundance, color = Source, 
                             fill = Source))+
  geom_point()+
  geom_smooth(method = 'lm')+
  scale_color_viridis_d()+
  scale_fill_viridis_d()+
  theme_bw(base_size = 20)+
  theme(legend.title = element_blank())

print(abund)

#These heat maps will look stupid for now because data was simuleated w/out covs
#But with real data it will be interesting to see if species cluster
#at certain sites
tru <- ggplot(data = long.tru, aes(x = Species, y = Site, fill = Abundance))+
  geom_tile()+
  scale_color_gradientn(colors = viridis_pal()(10), limits = c(1,16), 
                       aesthetics = "fill")+
  ggtitle("True")+
  scale_x_discrete(expand = c(0,0.5))+
  theme_classic(base_size = 12)+
  theme(legend.position = "none")

obs <- ggplot(data = long.obs, aes(x = Species, y = Site, fill = Abundance))+
  geom_tile()+
  scale_color_gradientn(colors = viridis_pal()(10), limits = c(1,16), 
                       aesthetics = "fill")+
  ggtitle("Observed")+
  theme_classic(base_size = 12)+
  scale_x_discrete(expand = c(0, 0.5))+
  theme(axis.title.y = element_blank())

heatplots <- tru+obs
print(heatplots)
```

Save as jpegs.
```{r}
ggsave(filename = "abundplot.jpeg", plot = abund)
ggsave(filename = "abundheat.jpeg", plot = heatplots, dpi = 750, 
       width = 8, units = "in")
```